arb-dir: lib/l10n
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
# optionnel :
# synthetic-package: false
# untranslated-messages-file: l10n_untranslated.txt
